version: '3.1'

networks:
    docker:

volumes:
    jenkins-data:
    jenkins-docker-certs:
services:

    jenkins:

        image: jenkinsci/blueocean
        user: root
        restart: always
        networks:
           -  docker
        ports:
           -  8080:8080
           -  50000:50000
        tty: true
        volumes:
           -  /var/run/docker.sock:/var/run/docker.sock
           -  jenkins-data:/var/jenkins_home

           -  jenkins-docker-certs:/certs/client

           -  /jenkins:/var/jenkins_home

        environment:
           -  DOCKER_HOST=tcp://docker:2376
           -  DOCKER_CERT_PATH=/certs/client
           -  DOCKER_TLS_VERIFY=1
   